### ISSUE TITLE
Pull requests from the original repo?

### ISSUE THREAD

**Issue by pjones** [standardsemiconductor/serialport#1]
First of all, thank you so much for taking over as maintainer of this package.

Do you have any plans to merge pull requests from the original repo?  I [have a PR](https://github.com/jputcu/serialport/pull/27) from 2015 that I think is useful.

Thanks again!

**Comment by dopamane** [comment]
Merged PR#2, thank you for your contribution! I will be releasing a new version (0.5.1) to Hackage this weekend with these updates included.

**Comment by pjones** [comment]
Great!  Thank you.
